environment:

  global:
      # Remember to edit .travis.yml too
      BUILD_COMMIT: a8ea658ce9aae96dc970866d98dd6eced734cd15
      #WHEELHOUSE_UPLOADER_USERNAME: travis-worker
      #WHEELHOUSE_UPLOADER_SECRET:
      #  secure:
      #      9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh

  matrix:
    - PYTHON_VERSION: "3.5"
      CONDAPATH: 'C:\Miniconda35'
    - PYTHON_VERSION: "3.6"
      CONDAPATH: 'C:\Miniconda36'
    - PYTHON_VERSION: "3.7"
      CONDAPATH: 'C:\Miniconda37'

#cache:
#  - '%LOCALAPPDATA%\pip\Cache'
#  - '%USERPROFILE%\.cache\matplotlib'

platform:
  - x64
  - x86


matrix:
  fast_finish: false

install:
  - git submodule update --init
  - if "%PLATFORM%" == "x64" set CONDAPATH=%CONDAPATH%-x64
  - call %CONDAPATH%\Scripts\activate
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q setuptools pandas wheel pip libpython cython
  - conda install -q -c msys2 m2w64-toolchain
  - cd pyreadstat
  - git fetch origin
  - git checkout %BUILD_COMMIT%
  - python.exe setup.py config --compiler=mingw32
  - python.exe setup.py bdist_wheel 
  - ps: "ls dist"
  - pip install --pre --no-index --find-links dist/ pyreadstat

build: off

test_script:
    python.exe tests\test_basic.py

#after_test:
  # This step builds your wheels.
  #- python.exe setup.py bdist_wheel

#artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  #- path: dist\*.whl

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
